version: '{branch}.{build}'
image: Visual Studio 2019
configuration: Release
before_build:
  ps: dotnet restore FluentAsync.sln
build:
  verbosity: minimal
after_test:
  ps: dotnet pack
artifacts:
  - path: /**/*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: AxJ2hSfFMgAz61VpY6qKM+IGTZW7SuDaUansoBBGx9kVoqj2V8rYbVrMo8/x7n7z
  skip_symbols: true
  artifact: /.*(\.|\.s)nupkg/
  on:
    APPVEYOR_REPO_TAG: true